import assert from 'node:assert/strict'
import { before, after, test } from 'node:test'
import { spawn } from 'node:child_process'
import { existsSync } from 'node:fs'
import { readFile } from 'node:fs/promises'
import { chromium } from 'playwright'

// Built application + isolated in-memory fixture. Never registers an account
// or writes to Supabase. Each case gets its own browser storage/session.
const base = 'http://127.0.0.1:5197'
const fixture = base + '/tests/ui-fixture.html'
let browser, server
async function startServer() {
  server = spawn(process.execPath, ['node_modules/vite/bin/vite.js', 'preview', '--outDir', 'tmp/pwa-test', '--host', '127.0.0.1', '--port', '5197', '--strictPort'], { stdio: ['ignore', 'pipe', 'pipe'] })
  let output = ''
  server.stdout.on('data', data => { output += data })
  server.stderr.on('data', data => { output += data })
  const ready = new Promise((resolve, reject) => {
    const timer = setTimeout(() => reject(new Error('Preview no preparado: ' + output)), 10_000)
    server.once('exit', code => { clearTimeout(timer); reject(new Error('Preview terminó: ' + code + ' ' + output)) })
    server.stdout.on('data', () => { if (output.includes(base)) { clearTimeout(timer); resolve() } })
  })
  await ready
  assert.equal((await fetch(base + '/connection.json')).ok, true)
}
async function stopServer() {
  const child = server
  server = null
  if (!child || child.exitCode !== null) return
  const closed = new Promise(resolve => child.once('exit', resolve))
  child.kill('SIGTERM')
  await closed
}
before(async () => {
  await startServer()
  const executablePath = process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || (existsSync('/usr/bin/chromium') ? '/usr/bin/chromium' : undefined)
  browser = await chromium.launch({ executablePath, headless: true })
})
after(async () => { await browser?.close(); await stopServer() })

async function withPage(action) {
  const context = await browser.newContext({ viewport: { width: 800, height: 480 } })
  const errors = []
  context.on('page', page => page.on('pageerror', error => errors.push(error.message)))
  // Prevent accidental real data traffic even if public variables are provided.
  await context.route('https://**.supabase.co/**', route => route.abort())
  const page = await context.newPage()
  page.setDefaultTimeout(10_000)
  try { await action(page, context); assert.deepEqual(errors, [], 'Sin errores de ejecución de la app') }
  finally { await context.close() }
}
async function visible(page, text) { await page.getByText(text, { exact: true }).waitFor({ state: 'visible' }) }
async function settings(page) { await page.getByRole('button', { name: 'AJUSTES', exact: true }).click() }
async function realMode(page) {
  await settings(page)
  await page.getByRole('button', { name: 'ON · NO GUARDAR PARTIDOS', exact: true }).click()
  await page.getByRole('button', { name: 'NUEVO PARTIDO', exact: true }).click()
}
async function selection(page, count = 2, goalLimit = 2) {
  await page.getByRole('button', { name: /PARTIDO RÁPIDO/ }).click()
  await page.getByRole('button', { name: /POR GOLES/ }).click()
  for (let i = 5; i > goalLimit; i--) await page.getByRole('button', { name: 'Reducir GOLES PARA GANAR' }).click()
  await page.getByRole('button', { name: 'SELECCIONAR JUGADORES ›' }).click()
  for (let i = 0; i < count; i++) await page.locator('.player-card').nth(i).click()
}
async function start(page) {
  await page.getByRole('button', { name: /COMENZAR/ }).click()
  await page.getByRole('button', { name: /PREPARADOS/ }).click()
}
async function whiteGoal(page) {
  const button = page.getByRole('button', { name: /BLANCO \d+ TOCAR PARA GOL/ })
  await page.waitForFunction(() => !document.querySelector('.white-score')?.disabled)
  await button.click()
}
async function finish(page) {
  await whiteGoal(page)
  await whiteGoal(page)
  await visible(page, 'FINAL DEL PARTIDO')
}
async function noOverflow(page) {
  // Resize events update React's visual viewport state on the next frame.
  await page.waitForFunction(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight)
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth && document.documentElement.scrollHeight <= innerHeight), true, 'Sin scroll general')
}
async function matchStorage(page) {
  return page.evaluate(() => Object.keys(localStorage).filter(key => key.includes(':active-match:') || key.includes(':pending:')).map(key => [key, localStorage.getItem(key)]))
}

test('build sin sesión: navegación responsive y preferencia física persistente', async () => withPage(async page => {
  await page.goto(base)
  for (const [width, height] of [[320, 568], [390, 844], [844, 390], [800, 480], [768, 1024], [1440, 900]]) {
    await page.setViewportSize({ width, height })
    await settings(page)
    assert.equal(await page.getByRole('textbox', { name: 'Correo' }).count(), 0, 'Settings no longer embeds Auth')
    await page.getByRole('navigation', { name: 'Acceso y cuenta' }).getByRole('button', { name: 'INICIAR SESIÓN', exact: true }).click()
    await page.getByRole('textbox', { name: 'Correo' }).waitFor()
    assert.equal(await page.getByRole('button', { name: 'ENTRAR', exact: true }).isDisabled(), true, 'Missing configuration does not send Auth')
    await noOverflow(page)
    await page.screenshot({ path: `/tmp/futbolin-account-layout-${width}-${height}.png` })
  }
  await settings(page)
  await page.getByRole('button', { name: 'PANTALLA 800×480' }).click()
  const box = await page.locator('.physical-canvas').boundingBox()
  assert.deepEqual({ width: box.width, height: box.height, x: box.x, y: box.y }, { width: 800, height: 480, x: 320, y: 210 })
  await page.reload()
  await page.locator('.physical-canvas').waitFor()
  await noOverflow(page)
}))

test('modo prueba: partido completo sin cola ni checkpoint', async () => withPage(async page => {
  await page.goto(fixture)
  await selection(page)
  await start(page)
  await finish(page)
  await visible(page, 'MODO PRUEBA · NO SE HA GUARDADO NADA')
  assert.deepEqual(await matchStorage(page), [])
  await page.getByRole('button', { name: 'RANKING', exact: true }).click()
  await visible(page, 'No hay partidos guardados.')
}))

test('nuevo partido: confirmación, No reanuda y Sí cancela sin generar resultado', async () => withPage(async page => {
  await page.clock.install()
  await page.goto(fixture); await realMode(page); await selection(page, 2, 5); await start(page)
  await whiteGoal(page)
  const original = JSON.parse((await matchStorage(page)).find(([key]) => key.includes(':active-match:'))[1])
  await page.getByRole('button', { name: 'NUEVO PARTIDO', exact: true }).click()
  await page.getByRole('dialog').waitFor()
  await page.getByRole('heading', { name: 'Hay un partido en curso. ¿Deseas cancelarlo?' }).waitFor()
  await page.clock.runFor(20_000)
  const paused = JSON.parse((await matchStorage(page)).find(([key]) => key.includes(':active-match:'))[1])
  assert.equal(paused.checkpoint.state.status, 'PAUSED'); assert.equal(paused.id, original.id)
  assert.equal(paused.checkpoint.state.elapsedSeconds, original.checkpoint.state.elapsedSeconds)
  await page.getByRole('button', { name: 'NO, CONTINUAR PARTIDO' }).click()
  await page.clock.runFor(1_100)
  assert.equal(await page.locator('.pause-overlay').count(), 0)
  const resumed = JSON.parse((await matchStorage(page)).find(([key]) => key.includes(':active-match:'))[1])
  assert.equal(resumed.id, original.id); assert.equal(resumed.checkpoint.state.whiteGoals, 1)
  assert.equal(resumed.checkpoint.state.status, 'PLAYING')
  await page.getByRole('button', { name: 'NUEVO PARTIDO', exact: true }).click()
  for (const [width, height] of [[320, 568], [390, 844], [800, 480]]) {
    await page.setViewportSize({ width, height }); await page.clock.runFor(100); await noOverflow(page)
    const dialog = await page.getByRole('dialog').boundingBox()
    assert.ok(dialog.x >= 0 && dialog.y >= 0 && dialog.x + dialog.width <= width && dialog.y + dialog.height <= height)
    await page.screenshot({ path: `/tmp/futbolin-cancel-${width}.png` })
  }
  await page.getByRole('button', { name: 'SÍ, CANCELAR PARTIDO' }).click()
  await page.getByRole('button', { name: /PARTIDO RÁPIDO/ }).waitFor()
  assert.equal((await matchStorage(page)).filter(([, value]) => value).length, 0)
  await page.reload(); assert.equal(await page.getByRole('button', { name: 'RECUPERAR PARTIDO' }).count(), 0)
  await page.getByRole('button', { name: 'RANKING', exact: true }).click(); await visible(page, 'No hay partidos guardados.')
}))

test('nuevo partido en prueba ON: cancelar countdown no guarda ni deja reloj activo', async () => withPage(async page => {
  await page.clock.install(); await page.goto(fixture); await selection(page, 2, 5)
  await page.getByRole('button', { name: /COMENZAR/ }).click()
  await page.getByRole('button', { name: 'NUEVO PARTIDO', exact: true }).click()
  await page.clock.runFor(10_000)
  assert.deepEqual(await matchStorage(page), [])
  await page.getByRole('button', { name: 'NO, CONTINUAR PARTIDO' }).click()
  await page.locator('.match-board').waitFor()
  assert.equal(await page.locator('.pause-overlay').count(), 0)
  await page.getByRole('button', { name: 'NUEVO PARTIDO', exact: true }).click()
  await page.getByRole('button', { name: 'SÍ, CANCELAR PARTIDO' }).click()
  await page.clock.runFor(100_000)
  await page.getByRole('button', { name: /PARTIDO RÁPIDO/ }).waitFor()
  assert.deepEqual(await matchStorage(page), [])
  assert.equal(await page.getByText('FINAL DEL PARTIDO', { exact: true }).count(), 0)
}))

test('recuperación: descarte confirmado conserva otras cuentas, jugadores y pendientes', async () => withPage(async page => {
  await page.goto(fixture); await realMode(page); await selection(page, 2, 5); await start(page); await whiteGoal(page)
  await page.reload(); await page.getByRole('button', { name: 'RECUPERAR PARTIDO' }).waitFor()
  for (const [width, height] of [[320, 568], [390, 844], [800, 480]]) {
    await page.setViewportSize({ width, height }); await noOverflow(page)
    const discard = page.getByRole('button', { name: 'DESCARTAR PARTIDO', exact: true })
    await discard.scrollIntoViewIfNeeded()
    assert.equal(await discard.evaluate(el => { const box = el.getBoundingClientRect(); return document.elementFromPoint(box.x + box.width / 2, box.y + box.height / 2) === el }), true)
    await page.screenshot({ path: `/tmp/futbolin-discard-recovery-${width}.png` })
  }
  await settings(page); await page.getByRole('button', { name: 'PANTALLA 800×480' }).click(); await page.reload()
  const physicalDiscard = page.getByRole('button', { name: 'DESCARTAR PARTIDO', exact: true })
  await physicalDiscard.scrollIntoViewIfNeeded()
  assert.equal(await physicalDiscard.evaluate(el => { const box = el.getBoundingClientRect(); return document.elementFromPoint(box.x + box.width / 2, box.y + box.height / 2) === el }), true, 'Descarte accesible en referencia física')
  const recoveryPlayers = page.locator('.recovery-players')
  await recoveryPlayers.scrollIntoViewIfNeeded()
  assert.ok((await recoveryPlayers.boundingBox()).height > 0, 'Los participantes no se comprimen hasta desaparecer')
  await physicalDiscard.scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/tmp/futbolin-discard-recovery-physical.png' })
  await page.evaluate(() => {
    const key = Object.keys(localStorage).find(key => key.includes(':active-match:'))
    const copy = JSON.parse(localStorage.getItem(key)); copy.ownerId = 'other-owner'
    localStorage.setItem(key.replace(/:[^:]+$/, ':other-owner'), JSON.stringify(copy))
    localStorage.setItem('unrelated:pending:other-owner', 'preserved-pending')
    localStorage.setItem('unrelated:players:other-owner', 'preserved-players')
  })
  const before = await page.evaluate(() => Object.fromEntries(Object.keys(localStorage).map(key => [key, localStorage.getItem(key)])))
  await page.getByRole('button', { name: 'DESCARTAR PARTIDO', exact: true }).click()
  await page.getByRole('button', { name: 'NO, CONSERVAR PARTIDO' }).click()
  assert.deepEqual(await page.evaluate(() => Object.fromEntries(Object.keys(localStorage).map(key => [key, localStorage.getItem(key)]))), before)
  await page.getByRole('button', { name: 'DESCARTAR PARTIDO', exact: true }).click()
  await page.getByRole('button', { name: 'SÍ, DESCARTAR PARTIDO' }).click()
  await page.getByRole('button', { name: /PARTIDO RÁPIDO/ }).waitFor()
  const after = await page.evaluate(() => Object.fromEntries(Object.keys(localStorage).map(key => [key, localStorage.getItem(key)])))
  for (const [key, value] of Object.entries(before)) {
    if (key.includes(':active-match:') && !key.endsWith(':other-owner')) assert.equal(after[key], '')
    else assert.equal(after[key], value, key + ' preserved')
  }
  await page.reload(); assert.equal(await page.getByRole('button', { name: 'RECUPERAR PARTIDO' }).count(), 0)
}))

test('cancelación: fallo de almacenamiento conserva el partido y permite continuar', async () => withPage(async page => {
  await page.goto(fixture); await realMode(page); await selection(page, 2, 5); await start(page); await whiteGoal(page)
  await page.getByRole('button', { name: 'NUEVO PARTIDO', exact: true }).click()
  const before = await matchStorage(page)
  await page.evaluate(() => {
    window.originalStorageSet = Storage.prototype.setItem
    Storage.prototype.setItem = function(key, value) {
      if (key.includes(':active-match:') && value === '') throw new Error('No se pudo escribir la copia local.')
      return window.originalStorageSet.call(this, key, value)
    }
  })
  await page.getByRole('button', { name: 'SÍ, CANCELAR PARTIDO' }).click()
  await page.getByRole('alert').filter({ hasText: 'El partido se conserva.' }).waitFor()
  assert.deepEqual(await matchStorage(page), before)
  await page.evaluate(() => { Storage.prototype.setItem = window.originalStorageSet })
  await page.getByRole('button', { name: 'NO, CONTINUAR PARTIDO' }).click()
  assert.equal(await page.locator('.match-board').count(), 1)
  await page.reload(); await page.getByRole('button', { name: 'RECUPERAR PARTIDO' }).waitFor()
}))

test('por goles: objetivo por equipo, cronómetro sin límite, sin partes y detalle guardado', async () => withPage(async page => {
  await page.clock.install()
  await page.goto(fixture)
  await realMode(page); await selection(page)
  await start(page)
  await page.clock.fastForward(600_000)
  await visible(page, 'POR GOLES · PRIMERO A 2 GOLES')
  await visible(page, 'TIEMPO JUGADO')
  assert.equal(await page.locator('.clock-panel strong').textContent(), '10:00')
  await whiteGoal(page); await page.clock.runFor(3_100)
  await page.locator('.blue-score').click()
  assert.equal(await page.locator('.match-board').count(), 1, '1–1 no termina con objetivo de dos')
  for (const [width, height] of [[320, 568], [390, 844], [800, 480]]) {
    await page.setViewportSize({ width, height }); await page.clock.runFor(100); await noOverflow(page)
  }
  await page.screenshot({ path: '/tmp/futbolin-single-goal-period.png' })
  await page.clock.runFor(3_100); await whiteGoal(page)
  await visible(page, 'FINAL DEL PARTIDO'); await visible(page, 'GANA BLANCO')
  await page.getByText('PARTIDO GUARDADO EN SUPABASE', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'RANKING', exact: true }).click()
  await page.locator('.history-list button').click()
  await visible(page, 'DETALLE DEL PARTIDO')
  assert.match(await page.locator('.history-summary').textContent(), /Primero a 2 · Sin partes · Sin límite de tiempo/)
  assert.equal(await page.locator('.event-list > div').count(), 5)
  assert.doesNotMatch(await page.locator('.event-list').textContent(), /SECOND_HALF|FINAL DE PARTE|PRÓRROGA|PENALTI/)
}))

test('ambas: objetivo total entre dos partes, recuperación y ganador acumulado', async () => withPage(async page => {
  await page.clock.install()
  await page.goto(fixture); await realMode(page)
  await page.getByRole('button', { name: /PARTIDO RÁPIDO/ }).click()
  await page.getByRole('button', { name: /AMBAS/ }).click()
  for (let i = 5; i > 1; i--) await page.getByRole('button', { name: 'Reducir DURACIÓN DE CADA PARTE' }).click()
  for (const [width, height] of [[320, 568], [390, 844], [800, 480]]) {
    await page.setViewportSize({ width, height }); await page.clock.runFor(100); await noOverflow(page)
    await page.getByRole('button', { name: 'Reducir DURACIÓN DE CADA PARTE' }).scrollIntoViewIfNeeded()
  }
  await page.screenshot({ path: '/tmp/futbolin-combined-configuration.png' })
  await page.getByRole('button', { name: 'SELECCIONAR JUGADORES ›' }).click()
  for (let i = 0; i < 2; i++) await page.locator('.player-card').nth(i).click()
  await start(page); await whiteGoal(page); await page.clock.runFor(3_100)
  await page.locator('.blue-score').click()
  assert.equal(await page.locator('.match-board').count(), 1, '1–1 no alcanza cinco goles por equipo')
  await page.clock.runFor(3_100); await whiteGoal(page)
  await page.clock.runFor(3_100); await page.locator('.blue-score').click()
  await page.clock.runFor(3_100); await whiteGoal(page)
  await visible(page, 'OBJETIVO TOTAL 5')
  assert.equal(await page.locator('.white-score strong').textContent(), '3')
  await page.clock.fastForward(60_000)
  await visible(page, 'FINAL DE LA 1ª PARTE')
  await page.getByRole('button', { name: 'CONTINUAR 2ª PARTE ›' }).click()
  await page.getByRole('button', { name: /PREPARADOS/ }).click()
  await whiteGoal(page)
  await visible(page, 'OBJETIVO TOTAL 5')
  assert.equal(await page.locator('.white-score strong').textContent(), '4')
  assert.equal(await page.locator('.blue-score strong').textContent(), '2')
  await page.clock.runFor(1_300)
  await page.screenshot({ path: '/tmp/futbolin-combined-global-target.png' })
  await page.reload(); await visible(page, 'PARTIDO POR RECUPERAR')
  const copy = await page.evaluate(() => JSON.parse(localStorage.getItem('marcador-ui-fixture:active-match:v1:fixture')))
  assert.equal(copy.checkpoint.version, 4)
  await page.getByRole('button', { name: 'RECUPERAR PARTIDO', exact: true }).click()
  await page.locator('.pause-overlay').getByRole('button', { name: 'CONTINUAR' }).click()
  await page.clock.runFor(3_100); await whiteGoal(page)
  await visible(page, 'FINAL DEL PARTIDO'); await visible(page, 'GANA BLANCO')
  await page.getByText('PARTIDO GUARDADO EN SUPABASE', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'RANKING', exact: true }).click()
  await page.locator('.history-list button').click()
  assert.match(await page.locator('.history-summary').textContent(), /BLANCO 5 — 2 AZUL.*AMBAS · Primero a 5 goles en total o dos partes de 1:00/)
}))

test('ambas: alcanzar el objetivo total en primera parte finaliza el partido', async () => withPage(async page => {
  await page.clock.install()
  await page.goto(fixture); await realMode(page)
  await page.getByRole('button', { name: /PARTIDO RÁPIDO/ }).click()
  await page.getByRole('button', { name: /AMBAS/ }).click()
  for (let i = 5; i > 2; i--) await page.getByRole('button', { name: 'Reducir GOLES PARA GANAR EL PARTIDO' }).click()
  await page.getByRole('button', { name: 'SELECCIONAR JUGADORES ›' }).click()
  for (let i = 0; i < 2; i++) await page.locator('.player-card').nth(i).click()
  await start(page); await whiteGoal(page)
  await page.clock.runFor(3_100); await page.locator('.blue-score').click()
  await page.clock.runFor(3_100); await whiteGoal(page)
  await visible(page, 'FINAL DEL PARTIDO'); await visible(page, 'GANA BLANCO')
  assert.equal(await page.getByRole('button', { name: 'CONTINUAR 2ª PARTE ›' }).count(), 0)
  await page.getByText('PARTIDO GUARDADO EN SUPABASE', { exact: true }).waitFor()
}))

test('por tiempo: dos partes completas, marcador acumulado y victoria 2–1', async () => withPage(async page => {
  await page.clock.install()
  await page.goto(fixture); await realMode(page)
  await page.getByRole('button', { name: /PARTIDO RÁPIDO/ }).click()
  await page.getByRole('button', { name: /POR TIEMPO/ }).click()
  assert.equal(await page.getByRole('button', { name: 'Reducir GOLES PARA GANAR' }).count(), 0)
  for (let i = 5; i > 1; i--) await page.getByRole('button', { name: 'Reducir DURACIÓN DE CADA PARTE' }).click()
  await page.screenshot({ path: '/tmp/futbolin-two-game-rules.png' })
  await page.getByRole('button', { name: 'SELECCIONAR JUGADORES ›' }).click()
  for (let i = 0; i < 2; i++) await page.locator('.player-card').nth(i).click()
  await start(page); await whiteGoal(page); await page.clock.runFor(3_100); await whiteGoal(page)
  await visible(page, '1ª PARTE')
  await page.clock.fastForward(60_000)
  await visible(page, 'FINAL DE LA 1ª PARTE')
  await page.getByRole('button', { name: 'CONTINUAR 2ª PARTE ›' }).click()
  await page.getByRole('button', { name: /PREPARADOS/ }).click()
  await visible(page, '2ª PARTE')
  assert.equal(await page.locator('.white-score strong').textContent(), '2')
  await page.locator('.blue-score').click()
  await page.clock.fastForward(60_000)
  await visible(page, 'FINAL DEL PARTIDO'); await visible(page, 'GANA BLANCO')
  assert.equal(await page.getByRole('button', { name: 'VER RESULTADO ›' }).count(), 0)
  await noOverflow(page)
  await page.screenshot({ path: '/tmp/futbolin-direct-final.png' })
  await page.getByText('PARTIDO GUARDADO EN SUPABASE', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'RANKING', exact: true }).click()
  await page.locator('.history-list button').click()
  assert.match(await page.locator('.history-summary').textContent(), /BLANCO 2 — 1 AZUL.*POR TIEMPO · Dos partes de 1:00/)
}))

test('ambas: segunda parte agotada sin alcanzar objetivo muestra ganador directamente', async () => withPage(async page => {
  await page.clock.install()
  await page.goto(fixture)
  await page.getByRole('button', { name: /PARTIDO RÁPIDO/ }).click()
  await page.getByRole('button', { name: /AMBAS/ }).click()
  for (let i = 5; i > 1; i--) await page.getByRole('button', { name: 'Reducir DURACIÓN DE CADA PARTE' }).click()
  await page.getByRole('button', { name: 'SELECCIONAR JUGADORES ›' }).click()
  for (let i = 0; i < 2; i++) await page.locator('.player-card').nth(i).click()
  await start(page); await page.locator('.blue-score').click()
  await page.clock.fastForward(60_000); await visible(page, 'FINAL DE LA 1ª PARTE')
  await page.getByRole('button', { name: 'CONTINUAR 2ª PARTE ›' }).click()
  await page.getByRole('button', { name: /PREPARADOS/ }).click()
  await page.clock.fastForward(60_000)
  await visible(page, 'FINAL DEL PARTIDO'); await visible(page, 'GANA AZUL')
  assert.equal(await page.getByRole('button', { name: 'VER RESULTADO ›' }).count(), 0)
  await visible(page, 'MODO PRUEBA · NO SE HA GUARDADO NADA')
  assert.deepEqual(await matchStorage(page), [])
}))

// Checklist 5: natural tied halves, golden goal and a full overtime to penalties.
for (const condition of ['POR TIEMPO', 'AMBAS']) {
  for (const goldenGoal of [true, false]) {
    test(`${condition}: empate lleva a prórroga y ${goldenGoal ? 'gol de oro' : 'penaltis alternos'}`, async () => withPage(async page => {
      await page.clock.install()
      await page.goto(fixture)
      await page.getByRole('button', { name: /PARTIDO RÁPIDO/ }).click()
      await page.getByRole('button', { name: new RegExp(condition) }).click()
      for (let i = 5; i > 1; i--) await page.getByRole('button', { name: 'Reducir DURACIÓN DE CADA PARTE' }).click()
      await page.getByRole('button', { name: 'SELECCIONAR JUGADORES ›' }).click()
      for (let i = 0; i < 2; i++) await page.locator('.player-card').nth(i).click()
      await start(page)
      await page.clock.fastForward(60_000); await visible(page, 'FINAL DE LA 1ª PARTE')
      await page.getByRole('button', { name: 'CONTINUAR 2ª PARTE ›' }).click()
      await page.getByRole('button', { name: /PREPARADOS/ }).click()
      await page.clock.fastForward(60_000); await visible(page, 'FINAL DE LA 2ª PARTE')
      await page.getByRole('button', { name: 'IR A PRÓRROGA ›' }).click()
      await page.getByRole('button', { name: /PREPARADOS/ }).click()
      await visible(page, 'PRÓRROGA · GOL DE ORO')
      assert.equal(await page.locator('.clock-panel strong').textContent(), '01:00')
      if (goldenGoal) {
        await page.locator('.blue-score').click()
        await visible(page, 'FINAL DEL PARTIDO'); await visible(page, 'GANA AZUL')
        assert.match(await page.locator('.result-score').textContent(), /BLANCO 0.*1 AZUL/)
        await page.screenshot({ path: `/tmp/futbolin-${condition === 'AMBAS' ? 'both' : 'time'}-golden-goal.png` })
      } else {
        await page.clock.fastForward(60_000); await visible(page, 'FINAL DE LA PRÓRROGA')
        await page.getByRole('button', { name: 'IR A PENALTIS ›' }).click()
        await page.getByRole('heading', { name: 'PENALTIS', exact: true }).waitFor()
        const white = page.locator('.white-penalty'), blue = page.locator('.blue-penalty')
        for (let kick = 0; kick < 3; kick++) {
          assert.equal(await white.getByRole('button', { name: 'GOL', exact: true }).isEnabled(), true)
          assert.equal(await blue.getByRole('button', { name: 'GOL', exact: true }).isDisabled(), true)
          await white.getByRole('button', { name: 'GOL', exact: true }).click()
          assert.equal(await white.getByRole('button', { name: 'GOL', exact: true }).isDisabled(), true)
          assert.equal(await blue.getByRole('button', { name: 'FALLO', exact: true }).isEnabled(), true)
          await blue.getByRole('button', { name: 'FALLO', exact: true }).click()
        }
        await visible(page, 'FINAL DEL PARTIDO'); await visible(page, 'GANA BLANCO')
        await visible(page, 'PENALTIS · BLANCO 3 — 0 AZUL')
        assert.match(await page.locator('.result-score').textContent(), /BLANCO 0.*0 AZUL/)
        await noOverflow(page)
        await page.screenshot({ path: `/tmp/futbolin-${condition === 'AMBAS' ? 'both' : 'time'}-penalties.png` })
      }
      await visible(page, 'MODO PRUEBA · NO SE HA GUARDADO NADA')
      assert.deepEqual(await matchStorage(page), [])
    }))
  }
}

test('vista protegida: cookie del mismo origen habilita acceso, sin cookie sigue bloqueado', async () => withPage(async (page, context) => {
  const probeRequests = []
  await context.route(base + '/connection.json', async route => {
    const cookies = (await route.request().allHeaders()).cookie ?? ''
    probeRequests.push(cookies.includes('preview-access-fixture=granted'))
    await route.fulfill(probeRequests.at(-1)
      ? { status: 200, contentType: 'application/json', body: JSON.stringify({ application: 'marcador-futbolin-v3' }) }
      : { status: 401, contentType: 'text/html', body: '<h1>Protected preview</h1>' })
  })
  await page.goto(fixture + '?auth=guest')
  await page.getByRole('navigation', { name: 'Acceso y cuenta' }).getByRole('button', { name: 'INICIAR SESIÓN', exact: true }).click()
  await page.getByRole('textbox', { name: 'Correo' }).fill('operator@example.invalid')
  await page.getByLabel('Contraseña', { exact: true }).fill('fixture-password-123')
  await page.waitForFunction(() => document.querySelector('.system-status')?.textContent.includes('SIN CONEXIÓN'))
  assert.equal(await page.getByRole('button', { name: 'ENTRAR', exact: true }).isDisabled(), true)
  assert.equal(await page.getByRole('button', { name: 'CREAR CUENTA', exact: true }).count(), 0)
  await page.getByRole('button', { name: 'IR AL REGISTRO DE CUENTA NUEVA' }).click()
  assert.equal(await page.getByRole('button', { name: 'CREAR CUENTA', exact: true }).isDisabled(), true)
  await page.getByRole('button', { name: 'VOLVER A INICIAR SESIÓN' }).click()
  await page.getByText(/El acceso está bloqueado porque/).waitFor()
  for (const [width, height] of [[320, 568], [390, 844], [800, 480]]) {
    await page.setViewportSize({ width, height })
    await noOverflow(page)
    await page.getByRole('button', { name: 'ENTRAR', exact: true }).scrollIntoViewIfNeeded()
  }
  await settings(page)
  await page.getByRole('button', { name: 'PANTALLA 800×480' }).click()
  await page.getByRole('navigation', { name: 'Acceso y cuenta' }).getByRole('button', { name: 'INICIAR SESIÓN', exact: true }).click()
  await noOverflow(page)
  const register = page.getByRole('button', { name: 'IR AL REGISTRO DE CUENTA NUEVA' })
  await register.scrollIntoViewIfNeeded()
  assert.equal(await register.evaluate(el => {
    const box = el.getBoundingClientRect()
    return document.elementFromPoint(box.x + box.width / 2, box.y + box.height / 2) === el
  }), true, 'El aviso no tapa el botón en la referencia física')
  await context.addCookies([{ name: 'preview-access-fixture', value: 'granted', domain: '127.0.0.1', path: '/', httpOnly: true, sameSite: 'Lax' }])
  await page.getByRole('button', { name: 'COMPROBAR CONEXIÓN', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.system-status')?.textContent.includes('SISTEMA ONLINE'))
  assert.equal(await page.getByRole('button', { name: 'ENTRAR', exact: true }).isDisabled(), false)
  await register.click()
  assert.equal(await page.getByRole('button', { name: 'CREAR CUENTA', exact: true }).isDisabled(), false)
  assert.ok(probeRequests.includes(false) && probeRequests.includes(true))
  // No Auth submission or real account creation; test only the UI prerequisite.
}))

test('acceso: entrar por botón o teclado no registra; registro separado requiere envío explícito', async () => withPage(async page => {
  await page.goto(fixture + '?auth=guest'); await page.getByRole('navigation', { name: 'Acceso y cuenta' }).getByRole('button', { name: 'INICIAR SESIÓN', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.system-status')?.textContent.includes('SISTEMA ONLINE'))
  await page.getByRole('heading', { name: 'INICIAR SESIÓN', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'CREAR CUENTA', exact: true }).count(), 0)
  await page.getByRole('textbox', { name: 'Correo' }).fill('operator@example.invalid')
  const password = page.getByLabel('Contraseña', { exact: true })
  await password.fill('fixture-password-123')
  await page.getByRole('button', { name: 'ENTRAR', exact: true }).click()
  await page.waitForFunction(() => window.fixtureAuthCalls.login === 1)
  await password.fill('fixture-password-123'); await password.press('Enter')
  await page.waitForFunction(() => window.fixtureAuthCalls.login === 2)
  assert.deepEqual(await page.evaluate(() => window.fixtureAuthCalls), { login: 2, register: 0 })
  await password.fill('fixture-password-123')
  for (const [width, height] of [[390, 844], [800, 480]]) {
    await page.setViewportSize({ width, height }); await noOverflow(page)
    await page.getByRole('button', { name: 'IR AL REGISTRO DE CUENTA NUEVA' }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: `/tmp/futbolin-login-separated-${width}.png` })
  }
  await page.getByRole('button', { name: 'IR AL REGISTRO DE CUENTA NUEVA' }).click()
  await page.getByRole('heading', { name: 'CREAR CUENTA NUEVA', exact: true }).waitFor()
  assert.equal(await password.inputValue(), '', 'El paso al registro no reutiliza la contraseña de acceso')
  assert.equal(await page.getByRole('button', { name: 'ENTRAR', exact: true }).count(), 0)
  assert.deepEqual(await page.evaluate(() => window.fixtureAuthCalls), { login: 2, register: 0 }, 'Abrir el registro no envía Auth')
  await page.getByLabel('Nombre de cuenta', { exact: true }).fill('OPERADOR DE PRUEBA')
  await password.fill('fixture-password-123')
  await page.getByLabel('Repetir contraseña', { exact: true }).fill('fixture-password-123')
  await page.getByRole('button', { name: 'CREAR CUENTA', exact: true }).click()
  await visible(page, 'Prueba local')
  assert.deepEqual(await page.evaluate(() => window.fixtureAuthCalls), { login: 2, register: 1 })
  await settings(page)
  await page.getByRole('button', { name: 'PANTALLA 800×480' }).click()
  await page.getByRole('navigation', { name: 'Acceso y cuenta' }).getByRole('button', { name: 'INICIAR SESIÓN', exact: true }).click()
  await noOverflow(page)
  await page.getByRole('button', { name: 'IR AL REGISTRO DE CUENTA NUEVA' }).click()
  await page.getByRole('button', { name: 'VOLVER A INICIAR SESIÓN' }).scrollIntoViewIfNeeded()
  await page.screenshot({ path: '/tmp/futbolin-registration-separated-physical.png' })
  await page.getByRole('button', { name: 'VOLVER A INICIAR SESIÓN' }).click()
  await page.getByRole('heading', { name: 'INICIAR SESIÓN', exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'CREAR CUENTA', exact: true }).count(), 0)
  assert.deepEqual(await page.evaluate(() => window.fixtureAuthCalls), { login: 2, register: 1 })
}))

test('recuperar contraseña: formulario separado, validación, sin registro ni login accidental', async () => withPage(async (page, context) => {
  await page.goto(fixture + '?auth=guest'); await page.getByRole('navigation', { name: 'Acceso y cuenta' }).getByRole('button', { name: 'INICIAR SESIÓN', exact: true }).click()
  await page.waitForFunction(() => document.querySelector('.system-status')?.textContent.includes('SISTEMA ONLINE'))
  await page.getByLabel('Correo', { exact: true }).fill('operator@example.invalid')
  await page.getByLabel('Contraseña', { exact: true }).fill('fixture-password-123')
  await page.getByRole('button', { name: 'RECUPERAR CONTRASEÑA', exact: true }).click()
  await page.getByRole('heading', { name: 'RECUPERAR CONTRASEÑA' }).waitFor()
  assert.equal(await page.getByLabel('Contraseña', { exact: true }).count(), 0)
  assert.equal(await page.getByLabel('Correo', { exact: true }).inputValue(), 'operator@example.invalid')
  assert.deepEqual(await page.evaluate(() => window.fixtureRecoveryCalls), { request: 0, update: 0 })
  await page.getByLabel('Correo', { exact: true }).fill('invalid')
  await page.getByRole('button', { name: 'ENVIAR ENLACE' }).click()
  assert.equal(await page.evaluate(() => window.fixtureRecoveryCalls.request), 0)
  await page.getByLabel('Correo', { exact: true }).fill('operator@example.invalid')
  await page.getByRole('button', { name: 'ENVIAR ENLACE' }).click()
  await visible(page, 'Si existe una cuenta con ese correo, recibirás un enlace para cambiar la contraseña.')
  assert.deepEqual(await page.evaluate(() => window.fixtureAuthCalls), { login: 0, register: 0 })
  assert.equal(await page.evaluate(() => window.fixtureRecoveryCalls.request), 1)
  for (const [width, height] of [[390, 844], [800, 480]]) {
    await page.setViewportSize({ width, height }); await noOverflow(page)
    await page.getByRole('button', { name: 'VOLVER A INICIAR SESIÓN' }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: `/tmp/futbolin-reset-request-${width}.png` })
  }
  await context.route(base + '/connection.json', route => route.fulfill({ status: 503 }))
  await context.setOffline(true)
  await page.waitForFunction(() => document.querySelector('.system-status')?.textContent.includes('SIN CONEXIÓN'))
  assert.equal(await page.getByRole('button', { name: 'ENVIAR ENLACE' }).isDisabled(), true)
  await page.getByRole('button', { name: 'VOLVER A INICIAR SESIÓN' }).click()
  assert.equal(await page.getByLabel('Contraseña', { exact: true }).inputValue(), '')
}))

test('retorno inválido: aviso seguro y parámetros de URL no habilitan cambio de contraseña', async () => withPage(async page => {
  await page.goto(fixture + '?auth=guest#error=access_denied&error_code=otp_expired&error_description=private-details')
  await page.getByRole('heading', { name: 'INICIAR SESIÓN' }).waitFor()
  await page.getByText(/No se pudo validar el enlace de acceso/).waitFor()
  assert.ok(!(await page.locator('body').innerText()).includes('private-details'))
  await page.getByRole('button', { name: 'RECUPERAR CONTRASEÑA', exact: true }).click()
  await page.getByRole('heading', { name: 'RECUPERAR CONTRASEÑA' }).waitFor()
  await page.goto(fixture + '?auth=guest#type=recovery&access_token=fixture')
  assert.equal(await page.getByRole('heading', { name: 'NUEVA CONTRASEÑA' }).count(), 0)
  assert.deepEqual(await page.evaluate(() => window.fixtureRecoveryCalls), { request: 0, update: 0 })
}))

test('enlace de recuperación: confirmación, guardado explícito y datos locales preservados', async () => withPage(async page => {
  await page.goto(fixture + '?auth=recovery')
  await page.getByRole('heading', { name: 'NUEVA CONTRASEÑA' }).waitFor()
  await page.waitForFunction(() => document.querySelector('.system-status')?.textContent.includes('SISTEMA ONLINE'))
  await page.evaluate(() => {
    localStorage.setItem('fixture-preserve-data', 'unchanged')
    sessionStorage.setItem('fixture-preserve-session-data', 'unchanged')
  })
  const password = page.getByLabel('Nueva contraseña', { exact: true })
  const confirmation = page.getByLabel('Repetir contraseña', { exact: true })
  await password.fill('new-fixture-password'); await confirmation.fill('different-password')
  await page.getByRole('button', { name: 'GUARDAR CONTRASEÑA' }).click()
  await visible(page, 'Las contraseñas no coinciden.')
  assert.equal(await page.evaluate(() => window.fixtureRecoveryCalls.update), 0)
  for (const [width, height] of [[390, 844], [800, 480]]) {
    await page.setViewportSize({ width, height }); await noOverflow(page)
    await page.screenshot({ path: `/tmp/futbolin-password-recovery-${width}.png` })
  }
  await confirmation.fill('new-fixture-password')
  await page.getByRole('button', { name: 'GUARDAR CONTRASEÑA' }).click()
  await visible(page, 'Contraseña actualizada. Ya puedes entrar con tu nueva contraseña.')
  assert.deepEqual(await page.evaluate(() => window.fixtureRecoveryCalls), { request: 0, update: 1 })
  assert.equal(await password.count(), 0)
  await page.getByRole('button', { name: 'VOLVER A MI CUENTA' }).click()
  await page.getByRole('heading', { name: 'MI CUENTA', exact: true }).waitFor()
  assert.deepEqual(await page.evaluate(() => [localStorage.getItem('fixture-preserve-data'), sessionStorage.getItem('fixture-preserve-session-data')]), ['unchanged', 'unchanged'])
}))

test('cabecera y mi cuenta: perfil, correo, seguridad y sesiones sin alterar datos', async () => withPage(async page => {
  await page.goto(fixture)
  const account = page.getByRole('navigation', { name: 'Acceso y cuenta' })
  await account.getByRole('button', { name: /MI CUENTA/ }).waitFor()
  for (const [width, height] of [[320, 568], [390, 844], [800, 480], [1280, 720]]) {
    await page.setViewportSize({ width, height }); await noOverflow(page)
    const box = await account.boundingBox()
    assert.ok(box.x + box.width <= width && box.y < 110, 'Acceso visible en la esquina superior')
  }
  await page.evaluate(() => localStorage.setItem('fixture-preserve-data', 'preserved'))
  await account.getByRole('button', { name: /MI CUENTA/ }).click()
  await page.getByRole('heading', { name: 'MI CUENTA', exact: true }).waitFor()
  await page.getByLabel('Nombre de cuenta', { exact: true }).fill('MI OPERADOR')
  await page.getByRole('button', { name: 'GUARDAR PERFIL' }).click()
  await visible(page, 'Perfil actualizado.')
  assert.equal(await page.evaluate(() => window.fixtureAccountCalls.profile), 1)
  await page.getByLabel('Nuevo correo', { exact: true }).fill('new-operator@example.invalid')
  await page.getByLabel('Contraseña actual', { exact: true }).fill('fixture-password')
  await page.getByRole('button', { name: 'SOLICITAR CAMBIO DE CORREO' }).click()
  await page.getByText('Confirmación pendiente: new-operator@example.invalid').waitFor()
  assert.equal(await page.getByLabel('Contraseña actual', { exact: true }).inputValue(), '')
  await page.getByRole('button', { name: 'SEGURIDAD', exact: true }).click()
  await page.getByLabel('Contraseña actual', { exact: true }).fill('fixture-password')
  await page.getByLabel('Nueva contraseña', { exact: true }).fill('new-fixture-password')
  await page.getByRole('button', { name: 'Mostrar nueva contraseña', exact: true }).click()
  assert.equal(await page.getByLabel('Nueva contraseña', { exact: true }).getAttribute('type'), 'text')
  await page.getByRole('button', { name: 'Ocultar nueva contraseña', exact: true }).click()
  await page.getByLabel('Repetir contraseña', { exact: true }).fill('different-password')
  await page.getByRole('button', { name: 'CAMBIAR CONTRASEÑA', exact: true }).click()
  await visible(page, 'Las contraseñas no coinciden.')
  assert.equal(await page.evaluate(() => window.fixtureAccountCalls.password), 0)
  await page.getByLabel('Repetir contraseña', { exact: true }).fill('new-fixture-password')
  await page.getByRole('button', { name: 'CAMBIAR CONTRASEÑA', exact: true }).click()
  await visible(page, 'Contraseña actualizada. Utilízala la próxima vez que inicies sesión.')
  assert.equal(await page.getByLabel('Nueva contraseña', { exact: true }).inputValue(), '')
  for (const [width, height] of [[390, 844], [800, 480]]) {
    await page.setViewportSize({ width, height }); await noOverflow(page)
    await page.getByLabel('Nueva contraseña', { exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: `/tmp/futbolin-account-security-${width}.png` })
  }
  await page.getByRole('button', { name: 'SESIONES', exact: true }).click()
  await page.getByRole('button', { name: 'CERRAR TODAS LAS SESIONES', exact: true }).click()
  assert.deepEqual(await page.evaluate(() => window.fixtureAccountCalls.logout), [])
  await page.getByRole('button', { name: 'CANCELAR', exact: true }).click()
  await page.getByRole('button', { name: 'CERRAR SESIÓN EN ESTE DISPOSITIVO' }).click()
  await account.getByRole('button', { name: 'INICIAR SESIÓN', exact: true }).waitFor()
  assert.deepEqual(await page.evaluate(() => window.fixtureAccountCalls.logout), ['local'])
  assert.equal(await page.evaluate(() => localStorage.getItem('fixture-preserve-data')), 'preserved')
}))

test('cuenta: cierre global explícito; partido en curso bloquea cambios y mantiene recuperación', async () => withPage(async page => {
  await page.goto(fixture)
  await page.getByRole('button', { name: /MI CUENTA/ }).click()
  await page.getByRole('button', { name: 'SESIONES', exact: true }).click()
  await page.getByRole('button', { name: 'CERRAR TODAS LAS SESIONES', exact: true }).click()
  await page.getByRole('button', { name: 'CONFIRMAR CIERRE EN TODOS LOS DISPOSITIVOS' }).click()
  await page.getByRole('navigation', { name: 'Acceso y cuenta' }).getByRole('button', { name: 'INICIAR SESIÓN' }).waitFor()
  assert.deepEqual(await page.evaluate(() => window.fixtureAccountCalls.logout), ['global'])
  await page.goto(fixture)
  await realMode(page); await selection(page, 2, 5); await start(page); await whiteGoal(page)
  const original = await matchStorage(page)
  await page.getByRole('button', { name: /MI CUENTA/ }).click()
  await page.getByText('Termina el partido y conserva su resultado antes de cambiar el acceso o cerrar sesión.').waitFor()
  assert.equal(await page.getByRole('button', { name: 'GUARDAR PERFIL' }).isDisabled(), true)
  await page.getByRole('button', { name: 'SESIONES', exact: true }).click()
  assert.equal(await page.getByRole('button', { name: 'CERRAR SESIÓN EN ESTE DISPOSITIVO' }).isDisabled(), true)
  assert.equal(await page.getByRole('button', { name: 'CERRAR TODAS LAS SESIONES' }).isDisabled(), true)
  const current = await matchStorage(page)
  assert.equal(current[0][0], original[0][0])
  const before = JSON.parse(original[0][1]); const after = JSON.parse(current[0][1])
  assert.equal(after.id, before.id); assert.deepEqual(after.players, before.players); assert.equal(after.checkpoint.state.whiteGoals, before.checkpoint.state.whiteGoals); assert.equal(after.checkpoint.state.blueGoals, before.checkpoint.state.blueGoals); assert.deepEqual(after.checkpoint.state.goals, before.checkpoint.state.goals); assert.deepEqual(after.checkpoint.state.events.slice(0, before.checkpoint.state.events.length), before.checkpoint.state.events)
  assert.equal(after.checkpoint.state.status, 'PAUSED')
  await page.getByRole('button', { name: 'NUEVO PARTIDO', exact: true }).click()
  await page.getByRole('button', { name: 'NO, CONTINUAR PARTIDO' }).click()
  await page.getByRole('button', { name: 'VOLVER AL PARTIDO' }).click()
  await page.locator('.pause-overlay').waitFor()
}))

test('seguridad: el código requerido por Auth se solicita explícitamente y valida antes del cambio', async () => withPage(async page => {
  await page.goto(fixture + '?account=reauth')
  await page.getByRole('button', { name: /MI CUENTA/ }).click()
  await page.getByRole('button', { name: 'SEGURIDAD', exact: true }).click()
  await page.getByLabel('Contraseña actual', { exact: true }).fill('fixture-current-password')
  await page.getByLabel('Nueva contraseña', { exact: true }).fill('fixture-new-password')
  await page.getByLabel('Repetir contraseña', { exact: true }).fill('fixture-new-password')
  await page.getByRole('button', { name: 'CAMBIAR CONTRASEÑA', exact: true }).click()
  await page.getByLabel('Código de seguridad', { exact: true }).waitFor()
  assert.deepEqual(await page.evaluate(() => [window.fixtureAccountCalls.reauthenticate, window.fixtureAccountCalls.password]), [0, 0])
  await page.getByRole('button', { name: 'ENVIAR CÓDIGO DE SEGURIDAD' }).click()
  await visible(page, 'Código enviado. Revisa tu correo.')
  await page.getByLabel('Código de seguridad', { exact: true }).fill('000000')
  await page.getByRole('button', { name: 'CAMBIAR CONTRASEÑA', exact: true }).click()
  await visible(page, 'El código de seguridad no es válido. Solicita uno nuevo e inténtalo otra vez.')
  assert.equal(await page.evaluate(() => window.fixtureAccountCalls.password), 0)
  await page.getByLabel('Código de seguridad', { exact: true }).fill('123456')
  await page.getByRole('button', { name: 'CAMBIAR CONTRASEÑA', exact: true }).click()
  await visible(page, 'Contraseña actualizada. Utilízala la próxima vez que inicies sesión.')
  assert.deepEqual(await page.evaluate(() => [window.fixtureAccountCalls.reauthenticate, window.fixtureAccountCalls.password]), [1, 1])
}))

test('correos: trece plantillas, enlaces nativos, código OTP y diseño adaptable sin tráfico', async () => withPage(async (page, context) => {
  await context.route('**/*', route => route.abort())
  const manifest = JSON.parse(await readFile('supabase/templates/manifest.json', 'utf8'))
  assert.equal(manifest.length, 13)
  for (const template of manifest) {
    const html = await readFile('supabase/templates/' + template.file, 'utf8')
    assert.ok(!/<script|<form|<input|https?:\/\//i.test(html), 'Static email without scripts, forms, external assets or tracking')
    if (['confirmation', 'recovery', 'email_change', 'magic_link', 'invite'].includes(template.name)) assert.equal((html.match(/href="{{ \.ConfirmationURL }}"/g) ?? []).length, 2)
    if (template.name === 'reauthentication') assert.ok(html.includes('{{ .Token }}'))
    if (template.kind === 'notification') assert.ok(!html.includes('.ConfirmationURL') && !html.includes('.Token'))
    const rendered = html.replace(/{{ \.ConfirmationURL }}/g, 'https://example.invalid/auth-fixture').replace(/{{ \.Token }}/g, '123456').replace(/{{ \.(\w+)(?: \| html)? }}/g, 'DATOS DE PRUEBA')
    await page.setViewportSize({ width: 390, height: 844 }); await page.setContent(rendered)
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true)
    assert.equal(await page.getByRole('heading', { level: 1 }).count(), 1)
    if (['confirmation', 'recovery'].includes(template.name)) await page.screenshot({ path: `/tmp/futbolin-email-${template.name}-390.png`, fullPage: true })
  }
}))

test('2v2: selección exacta, bloqueo, recarga en pausa y misma identidad del partido', async () => withPage(async page => {
  await page.goto(fixture)
  await realMode(page)
  await selection(page, 3, 3)
  assert.equal(await page.getByRole('button', { name: /COMENZAR/ }).isDisabled(), true)
  await page.locator('.player-card').nth(3).click()
  await start(page)
  await whiteGoal(page)
  assert.equal(await page.locator('.blue-score').isDisabled(), true)
  const original = await page.evaluate(() => JSON.parse(localStorage.getItem('marcador-ui-fixture:active-match:v1:fixture')))
  assert.equal(original.checkpoint.version, 2)
  await page.reload()
  await visible(page, 'PARTIDO POR RECUPERAR')
  assert.match(await page.locator('.recovery-meta').textContent(), /POR GOLES · PRIMERO A 3 GOLES/)
  await page.getByRole('button', { name: 'RECUPERAR PARTIDO', exact: true }).click()
  await page.locator('.pause-overlay').waitFor()
  assert.equal(await page.locator('.white-score strong').textContent(), '1')
  const recovered = await page.evaluate(() => JSON.parse(localStorage.getItem('marcador-ui-fixture:active-match:v1:fixture')))
  assert.equal(recovered.id, original.id)
  assert.equal(recovered.checkpoint.version, 2)
  assert.equal(recovered.checkpoint.state.elapsedSeconds, original.checkpoint.state.elapsedSeconds)
  assert.equal(recovered.players.length, 4)
  for (const [width, height] of [[390, 844], [844, 390], [800, 480]]) {
    await page.setViewportSize({ width, height })
    await noOverflow(page)
    assert.equal(await page.locator('.white-score strong').textContent(), '1')
  }
}))

test('resultado pendiente: recarga, reintento automático, historial sin duplicados', async () => withPage(async page => {
  await page.goto(fixture + '?save=offline')
  await realMode(page)
  await selection(page)
  await start(page)
  await finish(page)
  await page.getByText(/PENDIENTE EN ESTE DISPOSITIVO/).first().waitFor()
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('marcador-ui-fixture:pending:v1:fixture')).length), 1)
  assert.equal(await page.evaluate(() => localStorage.getItem('marcador-ui-fixture:active-match:v1:fixture')), '')
  await page.goto(fixture)
  await page.waitForFunction(() => localStorage.getItem('marcador-ui-fixture:pending:v1:fixture') === '[]')
  await page.getByRole('button', { name: 'RANKING', exact: true }).click()
  await page.locator('.history-list button').waitFor()
  assert.equal(await page.locator('.history-list button').count(), 1)
  await page.locator('.history-list button').click()
  await visible(page, 'DETALLE DEL PARTIDO')
  assert.equal(await page.locator('.event-list > div').count(), 4)
}))

function metric(page, label) { return page.locator('.statistics-grid > div').filter({ has: page.getByText(label, { exact: true }) }).locator('dd') }
async function profile(page, name) {
  await page.getByRole('button', { name: 'RANKING', exact: true }).click()
  await page.getByRole('button', { name: 'ESTADÍSTICAS', exact: true }).click()
  await page.locator('.statistics-players button').filter({ hasText: name }).click()
  await page.locator('.statistics-grid').waitFor()
}
test('perfil tras guardado/reintento: perspectiva, edición y snapshot histórico', async () => withPage(async page => {
  await page.goto(fixture)
  await realMode(page); await selection(page, 4); await start(page); await finish(page)
  await page.getByText('PARTIDO GUARDADO EN SUPABASE', { exact: true }).waitFor()
  await page.getByRole('button', { name: 'REINTENTAR GUARDADO' }).click()
  await profile(page, 'BLANCO DOS')
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '1')
  assert.equal(await metric(page, 'VICTORIAS').textContent(), '1')
  assert.equal(await metric(page, 'GOLES A FAVOR').textContent(), '2')
  await page.getByRole('button', { name: 'JUGADORES', exact: true }).click()
  await page.locator('.statistics-players button').filter({ hasText: 'AZUL DOS' }).click()
  await page.locator('.statistics-grid').waitFor()
  assert.equal(await metric(page, 'DERROTAS').textContent(), '1')
  assert.equal(await metric(page, 'GOLES EN CONTRA').textContent(), '2')
  await settings(page)
  await page.getByRole('button', { name: 'JUGADORES', exact: true }).click()
  const row = page.locator('.player-list-row').filter({ hasText: 'AZUL DOS' })
  await row.getByRole('button', { name: 'EDITAR', exact: true }).click()
  await page.getByRole('textbox', { name: 'Alias', exact: true }).fill('AZUL RENOMBRADO')
  await page.getByRole('button', { name: 'GUARDAR JUGADOR' }).click()
  await page.locator('.player-list-row').filter({ hasText: 'AZUL RENOMBRADO' }).getByRole('button', { name: 'PERFIL' }).click()
  await page.locator('.statistics-grid').waitFor()
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '1')
  await page.getByRole('button', { name: 'VER HISTORIAL DEL JUGADOR' }).click()
  await page.locator('.history-list button').waitFor()
  assert.equal(await page.locator('.history-list button').count(), 1)
  assert.match(await page.locator('.history-list button').textContent(), /AZUL DOS/)
  await page.locator('.history-list button').click()
  await visible(page, 'DETALLE DEL PARTIDO')
  assert.match(await page.locator('.history-summary').textContent(), /BLANCO UNO.*AZUL UNO.*BLANCO DOS.*AZUL DOS/)
}))

test('perfil completo: 25 resultados, inactivos, penaltis, historial paginado y ambas vistas', async () => withPage(async page => {
  await page.goto(fixture + '?statistics=seed')
  await profile(page, 'AZUL DOS')
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '25')
  assert.equal(await metric(page, 'VICTORIAS').textContent(), '2')
  assert.equal(await metric(page, 'DERROTAS').textContent(), '23')
  assert.equal(await metric(page, 'GOLES A FAVOR').textContent(), '3')
  assert.equal(await metric(page, 'GOLES EN CONTRA').textContent(), '48')
  assert.equal(await metric(page, 'VICTORIAS %').textContent(), '8%')
  for (const [width, height] of [[390, 844], [800, 480], [768, 1024], [1440, 900]]) {
    await page.setViewportSize({ width, height }); await noOverflow(page)
  }
  await page.getByRole('button', { name: 'VER HISTORIAL DEL JUGADOR' }).click()
  await page.locator('.history-list button').first().waitFor()
  assert.equal(await page.locator('.history-list button').count(), 20)
  await page.getByRole('button', { name: 'SIGUIENTES' }).click()
  await page.waitForFunction(() => document.querySelectorAll('.history-list button').length === 5)
  await page.getByRole('button', { name: 'VOLVER AL PERFIL' }).click()
  await page.locator('.statistics-grid').waitFor()
  await page.getByRole('button', { name: 'JUGADORES', exact: true }).click()
  await page.getByRole('searchbox', { name: 'Buscar jugador' }).fill('SIN PARTIDOS')
  await page.locator('.statistics-players button').click()
  await visible(page, 'No hay partidos guardados para este jugador.')
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '0')
  await settings(page)
  await page.getByRole('button', { name: 'PANTALLA 800×480' }).click()
  await profile(page, 'AZUL DOS')
  await page.locator('.physical-canvas').waitFor(); await noOverflow(page)
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '25')
  const historyButton = await page.getByRole('button', { name: 'VER HISTORIAL DEL JUGADOR' }).boundingBox()
  assert.ok(historyButton.y + historyButton.height <= await page.locator('.app-content').evaluate(el => el.getBoundingClientRect().bottom), 'Historial accesible sin desplazar los controles')
  await page.getByRole('button', { name: 'VER HISTORIAL DEL JUGADOR' }).click()
  await page.locator('.history-list button').first().waitFor()
  await noOverflow(page)
}))

test('perfil con error o sin red: no mostrar ceros como datos reales', async () => withPage(async (page, context) => {
  await page.goto(fixture + '?statistics=error')
  await page.getByRole('button', { name: 'RANKING', exact: true }).click()
  await page.getByRole('button', { name: 'ESTADÍSTICAS', exact: true }).click()
  await page.locator('.statistics-players button').filter({ hasText: 'BLANCO UNO' }).click()
  await page.getByText(/Error de consulta simulado/).first().waitFor()
  assert.equal(await page.locator('.statistics-grid').count(), 0)
  await context.setOffline(true)
  await page.waitForFunction(() => document.querySelector('.system-status')?.textContent.includes('SIN CONEXIÓN'))
  await page.getByText(/Las estadísticas necesitan consultar/).waitFor()
  assert.equal(await page.locator('.statistics-grid').count(), 0)
}))

test('análisis: rachas, formatos, filtros coherentes, historial y evolución', async () => withPage(async (page, context) => {
  await page.goto(fixture + '?statistics=analysis')
  await profile(page, 'BLANCO UNO')
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '12')
  assert.equal(await metric(page, 'VICTORIAS').textContent(), '4')
  assert.equal(await metric(page, 'DERROTAS').textContent(), '8')
  assert.match(await page.locator('.streak-grid').textContent(), /2 · DERROTA/)
  assert.equal(await page.locator('.format-table tbody tr').count(), 2)
  assert.equal(await page.locator('.format-table tbody tr').first().locator('td').first().textContent(), '6')
  assert.equal(await page.locator('.recent-results li').count(), 5)
  assert.match(await page.locator('.recent-results li').first().textContent(), /DERROTA · 1–1 · PENALTIS/)
  await page.getByText('FILTRAR ANÁLISIS', { exact: true }).click()
  await page.getByLabel('Desde', { exact: true }).fill('2026-10-04')
  await page.getByLabel('Hasta', { exact: true }).fill('2026-10-10')
  await page.getByLabel('Modalidad', { exact: true }).selectOption('QUICK')
  await page.getByLabel('Formato', { exact: true }).selectOption('2v2')
  // Draft changes do not silently change totals before applying.
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '12')
  await page.getByRole('button', { name: 'APLICAR FILTROS', exact: true }).click()
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '2')
  assert.equal(await metric(page, 'VICTORIAS %').textContent(), '100%')
  assert.match(await page.locator('.streak-grid').textContent(), /2 · VICTORIA/)
  assert.equal(await page.locator('.recent-results li').count(), 2)
  assert.equal(await page.locator('.format-table tbody tr').first().locator('td').first().textContent(), '0')
  await page.getByRole('button', { name: 'VER HISTORIAL DEL JUGADOR' }).click()
  await page.waitForFunction(() => document.querySelectorAll('.history-list button').length === 2)
  await page.locator('.history-list button').first().click()
  await visible(page, 'DETALLE DEL PARTIDO')
  assert.match(await page.locator('.history-summary').textContent(), /BLANCO DOS.*AZUL DOS/)
  await page.getByRole('button', { name: 'VOLVER AL PERFIL' }).click()
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '2')
  await page.getByLabel('Desde', { exact: true }).fill('2026-10-11')
  await page.getByRole('button', { name: 'APLICAR FILTROS', exact: true }).click()
  await page.getByRole('alert').filter({ hasText: /Desde debe/ }).waitFor()
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '2', 'Rango inválido conserva filtro anterior')
  await page.getByRole('button', { name: 'QUITAR FILTROS', exact: true }).click()
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '12')
  await page.getByRole('button', { name: 'ACTUALIZAR', exact: true }).click()
  await page.locator('.statistics-grid').waitFor()
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '12')
  await page.getByText('VER ÚLTIMOS 10 VALORES', { exact: true }).click()
  assert.equal(await page.locator('.evolution-values tbody tr').count(), 10)
  assert.equal(await page.locator('.evolution-values tbody tr').last().locator('td').last().textContent(), '33,3%')
  for (const [width, height] of [[320, 568], [390, 844], [844, 390], [800, 480], [768, 1024], [1440, 900]]) {
    await page.setViewportSize({ width, height }); await noOverflow(page)
    await page.getByRole('button', { name: 'VER HISTORIAL DEL JUGADOR' }).click()
    await page.locator('.history-list button').first().waitFor()
    await noOverflow(page)
    await page.getByRole('button', { name: 'VOLVER AL PERFIL' }).click()
  }
  await settings(page)
  await page.getByRole('button', { name: 'PANTALLA 800×480' }).click()
  await profile(page, 'BLANCO UNO')
  await page.getByText('FILTRAR ANÁLISIS', { exact: true }).click()
  await page.getByLabel('Formato', { exact: true }).selectOption('1v1')
  await page.getByRole('button', { name: 'APLICAR FILTROS', exact: true }).click()
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '6')
  await noOverflow(page)
  await page.getByRole('button', { name: 'VER HISTORIAL DEL JUGADOR' }).click()
  await page.locator('.history-list button').first().waitFor()
  await context.setOffline(true)
  await page.getByText(/Las estadísticas necesitan consultar/).waitFor()
  assert.equal(await page.locator('.statistics-grid').count(), 0)
  assert.equal(await page.locator('.analysis-details').count(), 0)
  await context.setOffline(false)
  await page.locator('.statistics-grid').waitFor()
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '6', 'Reconectar conserva el filtro y vuelve a leer')
}))

test('filtro sin resultados: ceros legítimos, sin gráfico y se puede quitar', async () => withPage(async page => {
  await page.goto(fixture + '?statistics=analysis')
  await profile(page, 'BLANCO UNO')
  await page.getByText('FILTRAR ANÁLISIS', { exact: true }).click()
  await page.getByLabel('Desde', { exact: true }).fill('2027-01-01')
  await page.getByRole('button', { name: 'APLICAR FILTROS', exact: true }).click()
  await visible(page, 'No hay partidos que coincidan con estos filtros.')
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '0')
  assert.equal(await page.locator('.victory-trend').count(), 0)
  await page.getByRole('button', { name: 'VER HISTORIAL DEL JUGADOR' }).click()
  await visible(page, 'No hay partidos guardados.')
  assert.equal(await page.locator('.history-list button').count(), 0)
  await page.getByRole('button', { name: 'VOLVER AL PERFIL' }).click()
  await page.getByRole('button', { name: 'QUITAR FILTROS', exact: true }).click()
  assert.equal(await metric(page, 'PARTIDOS').textContent(), '12')
  assert.equal(await page.locator('.victory-trend').count(), 1)
}))

test('PWA real: servidor apagado, reapertura y recuperación offline', async () => withPage(async (page, context) => {
  await page.goto(fixture + '?network=real')
  await realMode(page)
  await settings(page)
  await visible(page, 'OFFLINE DISPONIBLE EN ESTE DISPOSITIVO')
  await page.waitForFunction(() => navigator.serviceWorker.controller !== null)
  await page.getByRole('button', { name: 'NUEVO PARTIDO', exact: true }).click()
  await selection(page, 2, 3)
  await start(page)
  await whiteGoal(page)
  await stopServer()
  await page.close()
  try {
    const reopened = await context.newPage()
    await reopened.goto(fixture + '?network=real')
    await visible(reopened, 'PARTIDO POR RECUPERAR')
    await reopened.getByRole('button', { name: 'RECUPERAR PARTIDO', exact: true }).click()
    await reopened.locator('.pause-overlay').waitFor()
    assert.equal(await reopened.locator('.white-score strong').textContent(), '1')
    await noOverflow(reopened)
  } finally { await startServer() }
}))
